---
version: 1
dependencies:
  galaxy: requirements.yml
additional_build_steps:
  prepend:
    - RUN pip3 install --upgrade pip setuptools
    - RUN dnf -y install gcc python3-devel libcurl-devel openssl-devel libxml2-devel
    - ENV PYCURL_SSL_LIBRARY=openssl
